#!/usr/bin/python -u

import sys
sys.path.append('.')

from seisflows.tools.configtools import getclass, GlobalStruct

mypath = sys.argv[1]
myclass = sys.argv[2]

PAR = GlobalStruct('parameters',mypath)
PATH = GlobalStruct('paths',mypath)

if __name__ == '__main__':

    # load class
    obj = getclass(myclass)()

    # call main
    obj.main()

