#!/bin/env python

import sys
from os.path import join

from seisflows.tools.code import loadjson
from seisflows.tools.config import ConfigObj, ParameterObj

PAR = ParameterObj('SeisflowsParameters')
PATH = ParameterObj('SeisflowsPaths')
OBJ = ConfigObj('SeisflowsObjects')

if __name__ == '__main__':
    mypath = sys.argv[1]

    parname = 'SeisflowsParameters.json'
    pathname = 'SeisflowsPaths.json'
    objname = 'SeisflowsObjects'

    parfile = join(mypath, parname)
    pathfile = join(mypath, pathname)

    PAR.update(loadjson(parfile))
    PATH.update(loadjson(pathfile))
    OBJ.load(objname, mypath)

    import system
    import preprocess
    import solver
    import postprocess
    import optimize
    import workflow

    system.check()
    preprocess.check()
    postprocess.check()
    solver.check()
    optimize.check()
    workflow.check()

    workflow.main()

