#!/usr/bin/python -u

import sys
sys.path.append('.')

from seisflows.tools.configure import getclass, ParameterObject

mypath = sys.argv[1]
myclass = sys.argv[2]

PAR = ParameterObject('parameters',mypath)
PATH = ParameterObject('paths',mypath)

if __name__ == '__main__':

    # load class
    obj = getclass(myclass)()

    # call main
    obj.main()

