version: 2

sphinx:
    builder: html
    configuration: docs/conf.py

python:
    version: 3.7
    install:
        - requirements: docs/requirements.txt
        - requirements: requirements.txt
        - method: setuptools
          path: .

conda:
    environment: docs/environment.yml
