name: seisflows
channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    - obspy
    - cartopy
    - pyyaml
    # Pyatoa requirements, ensure they are installed via Conda
    - pyasdf 
    - pillow
    - pypdf2
    # Install Pyatoa via Pip which will install adjTomo tools
    - pip:
      - git+https://github.com/adjtomo/pyatoa@devel
      - -e .
       
