name: seisflows
channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    - obspy
    - cartopy
    - pyyaml
    # Pyatoa requirements, ensure they are installed via Conda
    - pyasdf 
    - pillow
    - pypdf2
    - pip:
      - -e .
       
