name: seisflows
channels:
    - conda-forge
dependencies:
    - pip
    - numpy<=1.24
    - obspy
    - cartopy
    - pyyaml
    - pypdf
    - pip:
      #- pyatoa>=0.4.0
      - git+https://github.com/adjtomo/pyatoa.git@devel
      - pysep-adjtomo
      - -e .

