#!/bin/bash -e
# ==============================================================================
# This is a Wisteria (UTokyo HPC) specific submit script that is required 
# because the compute node does not inherit the login node's Conda environment.
# Instead we need to load the module and environment manually, before submit
# ==============================================================================

# Defines where our Conda environment is stored
WORK_DIR=/work/01/gr58/share/adjtomo

# Load MPI and activate Conda environment
module load intel
module load impi
module load miniconda/py38_4.9.2
source $MINICONDA_DIR/etc/profile.d/conda.sh
conda activate $WORK_DIR/conda/envs/adjtomo 

# Submit Workflow: ensure that we are using the correct Python version 
$WORK_DIR/conda/envs/adjtomo/bin/python $WORK_DIR/REPOSITORIES/seisflows/seisflows/system/runscripts/submit --workdir $PJM_O_WORKDIR --parameter_file parameters.yaml 
