#!/bin/bash -e

# This is a Wisteria (UTokyo HPC) specific submit script that is required 
# because the compute node does not inherit the login node's Conda environment.
# Instead we need to load the module and environment manually, before submit

module load miniconda/py38_4.9.2
source $MINICONDA_DIR/etc/profile.d/conda.sh
conda activate /work/01/gr58/share/adjtomo/conda/envs/adjtomo 
./submit
