#!/bin/bash -e


WARNING="
This test works only on tiger.princeton.edu
"
if [ $(hostname) != tiger1 ] && [ $(hostname) != tiger2 ]; then
   echo $WARNING
   exit
fi


cd $(dirname ${BASH_SOURCE[0]})
WD="$PWD/setup/test_checkers_2d"
mkdir $WD


# copy parameters and paths
cp /home/rmodrak/data/Examples2d/checkers/parameters.py $WD/parameters
cp /home/rmodrak/data/Examples2d/checkers/paths.py $WD/paths


# run tests
sfrun --workdir=$WD --parameter_file=$WD/parameters --path_file=$WD/paths


COMPARE="/home/rmodrak/tools/seistools/compare_models --parameters=vs"
MODEL="$WD/output/model_0001"
MODEL0="/home/rmodrak/data/Examples2d/checkers/ref/model_0001"


# wait until first iteration completes
until [ -e $MODEL ]; do
    sleep 1
done


# compare output with reference model
$COMPARE $MODEL $MODEL0


# comment out to preserve output for inspection
rm -rf $WD



