#!/bin/bash

# navigate to seisflows/tests directory
cd $(dirname ${BASH_SOURCE[0]})


WD="$PWD/setup/test_system"


# test serial
sfrun --workdir=$WD --parameter_file=$WD/parameters_serial --path_file=$WD/paths
rm -rf $WD/output* $WD/scratch


# test multithreaded
sfrun --workdir=$WD --parameter_file=$WD/parameters_multithreaded --path_file=$WD/paths
rm -rf $WD/output* $WD/scratch


