#!/usr/bin/python -u

import os
import sys

mypath = sys.argv[1]
myclass = sys.argv[2]

os.chdir(mypath)

from seisflows.tools.config import loadclass, ParameterObj

PAR = ParameterObj('parameters',mypath)
PATH = ParameterObj('paths',mypath)

if __name__ == '__main__':

    # load class
    obj = loadclass(myclass)()

    # call main
    obj.main()

