#!/usr/bin/python -u

import os
import sys

mypath = sys.argv[1]
myclass = sys.argv[2]

os.chdir(mypath)

from seisflows.tools.configtools import getclass, GlobalStruct

PAR = GlobalStruct('parameters',mypath)
PATH = GlobalStruct('paths',mypath)

if __name__ == '__main__':

    # load class
    obj = getclass(myclass)()

    # call main
    obj.main()

