#!/bin/bash

path=$1
class=$2
func=$3
exe=$4
hosts=$( echo $5 | tr ',' ' ' )

k=0;
for host in $hosts;
do
    ssh $host "export SEISFLOWS_TASK_ID=$k; $exe $path $class $func" &
    k=$((k+1));
done
wait

