#!/usr/bin/env python
"""
A wrapper for running tasks within the currently executing workflow
"""
import os
import sys

from seisflows.tools.tools import loadjson, loadobj
from seisflows.config import load

def export(myenv):
    """
    Exports comma delimited list of environment variables

    e.g. VARNAME1=value1,VARNAME2=value2

    :type myenv: str
    :param myevn: the system environment to take variables from
    """
    for item in myenv.split(','):
        os.environ.update([item.split('=')])


if __name__ == '__main__':
    """ 
    Runs task within currently executing workflow
    """
    nargs = len(sys.argv[1:])

    # Parse command line arguments
    mypath = sys.argv[1]
    myclass = sys.argv[2]
    myfunc = sys.argv[3]

    if nargs == 4: 
        myenv = sys.argv[4].strip(',')
        export(myenv)

    # Reload from last checkpoint
    load(mypath)

    # Load function arguments
    kwargspath = os.path.join(mypath, 'kwargs')
    kwargs = loadobj(os.path.join(kwargspath, f"{myclass}_{myfunc}.p"))

    # Call function
    func = getattr(sys.modules[f"seisflows_{myclass}"], myfunc)
    func(**kwargs)

