#!/usr/bin/env python

if __name__ == '__main__':
    import sys

    # parse command line arguments
    mypath = sys.argv[1]
    myclass = sys.argv[2]
    myfunc = sys.argv[3]

    from os.path import join
    from seisflows.tools.code import loadjson, loadobj
    from seisflows.config import load

    # reload from last checkpoint
    load(mypath)

    if sys.modules['seisflows_system'].getnode() == 0:
        # load function arguments
        kwargspath = join(mypath, 'kwargs')
        kwargs = loadobj(join(kwargspath, myclass+'_'+myfunc + '.p'))

        # call function
        func = getattr(sys.modules['seisflows_'+myclass], myfunc)
        func(**kwargs)

