#!/usr/bin/env python

# Specialized script used to visualize seismic section.

import argparse

from obspy import read
import matplotlib.pyplot as plt

from seisflows.tools.graphics import plot_section


def parse_args():
    # Parse input arguments
    parser = argparse.ArgumentParser(description='Plot seismic section from SU data file.')

    # file and format flags
    parser.add_argument('file',
                        help='SU filename')

    parser.add_argument('-cm', '--cmap', default='seismic',
                        help='Matplotlib colormap scheme.')

    parser.add_argument('-c', '--clip', type=float,
                        default='0',
                        help='Clip amplitudes [0-100]')

    parser.add_argument('-t', '--title', type=str,
                        default='',
                        help='Plot title.')

    parser.add_argument('-xint', '--x_interval', type=float,
                        default='1.0',
                        help='Offset axis tick spacing [km].')

    parser.add_argument('-yint', '--y_interval', type=float,
                        default='1.0',
                        help='Time axis tick spacing [s].')

    return parser.parse_args()


if __name__ == "__main__":

    args = parse_args()

    if args.clip < 0:
        args.clip = 0
    elif args.clip > 100:
        args.clip = 100

    stream = read(args.file, format='SU', byte_order='<')
    plot_section(stream,
                 cmap=args.cmap,
                 clip=(100-args.clip),
                 title=args.title,
                 x_interval=args.x_interval,
                 y_interval=args.y_interval)
    plt.show()