#!/usr/bin/python

import sys
import numpy as np

from seisflows.seistools.arraytools import gridplot


if __name__ == '__main__':
    """ Plots data on 2-D rectangular grid

        Reads data from text file and plots it using matplotlib
    """
    filename  = sys.argv[1]

    Z = np.loadtxt(filename)
    print Z.shape

    ny = Z.shape[0]
    nx = Z.shape[1]
    nxmax = 750
    nymax = 750

    if ny > nymax:
      iy = int(np.ceil(ny/nymax))
      iy = range(0,ny,iy)
    else:
      iy = range(0,ny)

    if nx > nxmax:
      ix = int(np.ceil(nx/nxmax))
      ix = range(0,nx,ix)
    else:
      ix = range(0,nx)

    gridplot(Z[np.ix_(iy,ix)])
