#!/usr/bin/python

import sys

import numpy as np

from seisflows.seistools import readsegy, readsu, splot, wplot


def filetype(filename):
    """ Decides filetype based on extension.

     Checks standard SU and SEGY extensions as well as extensions in use by
     SPECFEM2D and SPECFEM3D. 
    """

    if ('.segy' in filename.lower()):
        return 'segy'

    elif ('.su' in filename.lower()):
        return 'su'

    elif ('single.bin' in filename):
        return 'su'

    elif ('single.adj' in filename):
        return 'su'

    elif ('_SU' in filename):
        return 'su'

    else:
        return None



if __name__ == '__main__':
  """ Plots record section read from SU or SEGY file
  """

  filename = sys.argv[1]

  if filetype(filename) == 'segy':
     s,h = readsegy(filename)

  elif filetype(filename) == 'su':
     s,h = readsu(filename)

  print 'ntraces:', s.shape[0]
  print 'nsamples:', s.shape[1]

  if len(sys.argv[1:]) == 1:
     print 'min, max:', s.min(), s.max()

     # plot record section
     splot(s,h)

  else:
    for ii in sys.argv[2:]:
      w = np.zeros((h.nt,2))
      w[:,0] = np.linspace(0,h.nt*h.dt,h.nt)
      w[:,1] = s[:,ii]

      # plot waveform
      wplot(w)

