#!/usr/bin/env python

import sys

import numpy as np

from seisflows.seistools import wplot


if __name__ == '__main__':
    """ Plots record section read from SU or SEGY file
    """

    for filename in sys.argv[1:]:

        w = np.loadtxt(filename)

        print ''
        print filename
        print 'min, max:', w[:, 1].min(), w[:, 1].max()
        print ''

        # plot waveform
        wplot(w)

