#!/bin/sh

usage="$(basename "$0") [-h] -- delete directories output* and scratch in the current directory

where:
    -h  show this help text"

while getopts ':hs:' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
  esac
done
shift $((OPTIND - 1))

rm -rf output*
rm -rf scratch

