#!/bin/sh
# This script deletes all the generated outputs of Seisflows, to reset back to
# the initial state. All intermediate data will be lost.

echo "Are you sure about that? (y/[n])"
read choice
if [ "$choice" == "y" ] 
then 
    rm -rf output*
    rm -rf error.log
    rm -rf scratch
    rm -rf pyatoa.io
fi
