#!/usr/bin/env python

import os
from sys import exit
from os.path import join

from seisflows.tools import unix
from seisflows.tools.code import exists

msg = """
To run examples, please install the seisflows-examples repository,
following the instructions at
http://seisflows-examples.readthedocs.org/en/latest/

Alternatively, tiger users can simply set the environment variable
SFEXAMPLES to /home/rmodrak/packages/seisflows-examples
"""


if __name__ == '__main__':
    """ Prompts user to select SEISFLOWS example, then sets up working
      directory to run example.
    """

    def listdir(dir):
        subdirs = []
        for subdir in unix.ls(dir):
            if os.path.isdir(dir+'/'+subdir):
                if subdir[0] != '_':
                    subdirs += [subdir]
        subdirs.sort()
        return subdirs

    path = os.getenv('SFEXAMPLES')
    if not exists(path):
       print(msg)
       exit()

    # prompt user for selections
    #opts = unix.ls(path)
    opts = ['Examples2d', 'Examples3d', 'Examples3dGlobe']
    opt = unix.select(opts)
    print ''
    path = join(path, opt)
    print ''

    dirs = listdir(path)
    prompt = 'select directory:'
    dir = unix.select(dirs, prompt)
    print ''

    items = unix.ls(path+'/'+dir)
    if 'parameters.py' in items:
        subdir = ''
    else:
        subdirs = listdir(path+'/'+dir)
        prompt = 'select subdirectory:'
        subdir = unix.select(subdirs, prompt)
        print ''

    # set up working directory
    fullpath = path+'/'+dir+'/'+subdir
    unix.cp(fullpath+'/'+'parameters.py', '.')
    unix.cp(fullpath+'/'+'paths.py', '.')

