#!/usr/bin/python

import os

from seisflows.tools import unix
from seisflows.tools.code import glob, join


def listdir(dir):
    subdirs = []
    for subdir in unix.ls(dir):
      if os.path.isdir(dir+'/'+subdir):
        if subdir[0] != '_':
          subdirs += [subdir]
    subdirs.sort()
    return subdirs


if __name__ == '__main__':
    """ Prompts user to select SEISFLOWS example, then sets up current working
        directory to run example. 

        Currently, this script only works on tiger.princeton.edu, but a version 
        that runs on any Unix machine is being developed.
    """

    # prompt user for path
    home = '/home/rmodrak/data/'
    opts = ['Examples2d','Examples3d','Examples3dGlobe']
    print ''
    path = join(home,unix.select(opts))
    print ''

    # prompt user for directory
    dirs = listdir(path)
    prompt = 'select directory:'
    dir = unix.select(dirs,prompt)
    print ''

    # prompt user for sudirectory
    items = unix.ls(path+'/'+dir)
    if 'parameters.py' in items:
      subdir = ''
    else:
      subdirs = listdir(path+'/'+dir)
      prompt = 'select subdirectory:'
      subdir = unix.select(subdirs,prompt)
      print ''

    # set up working directory
    fullpath = path+'/'+dir+'/'+subdir
    unix.cp(fullpath+'/'+'parameters.py','.')
    unix.cp(fullpath+'/'+'paths.py','.')

