#!/usr/bin/env python

from seisflows.tools.config import SeisflowsParameters, SeisflowsPaths, \
    SeisflowsObjects

for obj in [SeisflowsParameters(), SeisflowsPaths()]:
   obj.load()

for obj in [SeisflowsObjects()]:
   obj.reload('./output')

import system
import workflow
system.submit(workflow)


