#!/usr/bin/env python

import sys

from seisflows.config import config, loadpy, tilde_expand, Dict

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument('workdir', nargs='?', default=os.getcwd())
    parser.add_argument('parameters_file', nargs='?', default='parameters.yaml')
    parser.add_argument('paths_file', nargs='?', default='paths.yaml')

    args = vars(parser.parse_args())


if __name__ == "__main__":
    ### workflow submission script

    # register parameters
    parameters = loadpy('parameters.py')
    sys.modules['seisflows_parameters'] = Dict(parameters)

    # register paths
    paths = tilde_expand(loadpy('paths.py'))
    sys.modules['seisflows_paths'] = Dict(paths)

    # register objects
    config()

    workflow = sys.modules['seisflows_workflow']
    system = sys.modules['seisflows_system']

    #cd(args.workdir)

    system.submit(workflow)

