#!/usr/bin/env python

import sys

from seisflows.config import config, loadpy, tilde_expand, Dict

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('workdir', nargs='?', default=os.getcwd())
    parser.add_argument('parameter_file', nargs='?', default='parameters.yaml')
    parser.add_argument('paths_file', nargs='?', default='paths.yaml')
    args = vars(parser.parse_args())


if __name__ == "__main__":
    ### workflow submission script

    args = parse_args()

    parameters = Dict(loadpy(args.parameters_file))
    paths = Dict(tilde_expand(loadpy(args.paths_file)))

    # register parameters and paths
    sys.modules['seisflows_parameters'] = parameters
    sys.modules['seisflows_paths'] = paths

    # instantiate and register objects
    config()

    # create handles
    workflow = sys.modules['seisflows_workflow']
    system = sys.modules['seisflows_system']

    cd(args.workdir)

    # submit workflow
    system.submit(workflow)


