#!/usr/bin/env python

import sys

from importlib import import_module
from pkgutil import iter_modules
from seisflows.config import Null

try:
    import matplotlib
except:
    matplotlib = False

try:
    import obspy
except:
    obspy = False

verbose = 1

succeeded = []
excluded = []
failed = []

def check_package(pkgname):
    if pkgname in excluded:
        return
    package = import_module(pkgname)
    for _, modname, ispkg in iter_modules(package.__path__):
        full_dotted_name = pkgname+'.'+modname
        if ispkg:
            check_package(full_dotted_name)
        else:
            check_module(full_dotted_name)


def check_module(name):
    global succeeded
    global excluded
    global failed

    if name in excluded:
        return
    try:
        import_module(name)
    except NotImplementedError:
        excluded += [name]
    except Exception as e:
        if verbose > 0:
            print name.upper()
            print e
            print '\n'
        failed += [name]
    else:
        succeeded += [name]


def initialize():
    # load dummy state
    names = []
    names += ['parameters']
    names += ['paths']
    names += ['system']
    names += ['optimize']
    names += ['preprocess']
    names += ['solver']
    names += ['postprocess']
    names += ['workflow']
    for name in names:
        sys.modules['seisflows_'+name] = Null()


# exclude modules from this list
excluded += ['seisflows.solver']
excluded += ['seisflows.workflow.test_optimize']
excluded += ['seisflows.workflow.test_preprocess']

if not matplotlib:
    excluded += ['seisflows.tools.graphics']

if not obspy:
    excluded += ['seisflows.preprocess.base']
    excluded += ['seisflows.preprocess.default']
    excluded += ['seisflows.preprocess.double_difference']



if __name__ == '__main__':

    initialize()

    # recursively check package
    check_package('seisflows')

    # disply results
    print '\n'
    print '%d modules were excluded' % len(excluded)
    print '\n'
    print '%d modules imported successfully' % len(succeeded)
    print '\n'
    print '%d modules failed to import' % len(failed)
    print '\n'

    if verbose > 1:
        if excluded:
            print 'The following modules were excluded:'
            for name in excluded: print '  %s' % name
            print '\n'

        if succeeded:
            print 'The following modules imported successfully:'
            for name in succeeded: print '  %s' % name
            print '\n'

        if failed:
            print 'The following modules failed to import:'
            for name in failed: print '  %s' % name
            print '\n'
        
    if failed:
        sys.exit(-1)
    else:
        print 'SUCCESS\n'


